apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform workloads managed by ArgoCD (prototype)
  sourceRepos:
    - "<YOUR_GIT_REPO_URL>"
    - "https://charts.jenkins.io"
    - "https://charts.bitnami.com/bitnami"
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: jenkins-dev
      server: https://kubernetes.default.svc
    - namespace: jenkins-stg
      server: https://kubernetes.default.svc
    - namespace: jenkins-prd
      server: https://kubernetes.default.svc
    - namespace: tf-state
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
