controller:
  admin:
    username: admin
    password: admin   # prototype only; later switch to existingSecret
  serviceType: ClusterIP
  installPlugins:
    - kubernetes:4310.vd33b_0869301f
    - workflow-aggregator:600.vb_57cdd26fdd7
    - git:5.5.2
    - configuration-as-code:1897.v79281e066ea_7
  JCasC:
    defaultConfig: true

agent:
  enabled: true
  image:
    repository: jenkins/inbound-agent
    tag: "3206.vb_15dcf73f6a_9-1"
