controller:
  admin:
    username: admin
    password: admin   # prototype only; later switch to existingSecret  
  serviceType: LoadBalancer
  serviceAnnotations: {}
  loadBalancerIP: 10.10.50.211

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  JCasC:
    defaultConfig: true

agent:
  enabled: true
  image:
    repository: jenkins/inbound-agent
    tag: "3206.vb_15dcf73f6a_9-1"
