controller:
  admin:
    username: admin
    password: admin   # prototype only; later switch to existingSecret  
  serviceType: LoadBalancer
  serviceAnnotations: {}
  loadBalancerIP: 10.10.50.213
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  JCasC:
    defaultConfig: true

agent:
  enabled: true
