controller:
  admin:
    username: admin
    password: admin
  serviceType: ClusterIP
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  JCasC:
    defaultConfig: true

agent:
  enabled: true
