auth:
  rootUser: minioadmin
  rootPassword: minioadmin  # prototype only; later switch to existingSecret

defaultBuckets: "tfstate"

persistence:
  enabled: true
  size: 20Gi

service:
  type: ClusterIP

image:
  registry: public.ecr.aws
  repository: bitnami/minio
  tag: 2024.9.9-debian-12-r0
