apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-prd
  namespace: argocd
spec:
  project: platform

  sources:
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 5.8.6
      helm:
        releaseName: jenkins-prd
        valueFiles:
          - $values/argocd/helm-values/jenkins/prd-values.yaml

    - repoURL: https://github.com/mimyrtek/platform-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-prd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
