apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform-project.yaml
  - jenkins-dev-app.yaml
  - jenkins-stg-app.yaml
  - jenkins-prd-app.yaml
  - minio-tfstate-app.yaml
