spec:
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 14.7.8
    helm:
      releaseName: minio-tfstate
      valueFiles:
      - $values/argocd/helm-values/minio/tfstate-values.yaml
  - ref: values
    repoURL: https://github.com/mimyrtek/platform-gitops.git
    targetRevision: main
