apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Platform workloads managed by ArgoCD (prototype)
  sourceRepos:
    - "https://github.com/mimyrtek/platform-gitops.git"
    - "https://charts.jenkins.io"
    - "https://charts.bitnami.com/bitnami"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
